theory mr17283_Strahinja_Trninic
  imports Main "HOL-Proofs-Extraction.Util" "HOL-Library.Realizers" "HOL-Library.Code_Target_Numeral"
begin

text \<open>
                      Isabelle projekat

Predmet: Uvod u interaktivno dokazivanje teorema
Profesor: prof. dr. Filip Maric
Asistent: prof. dr. Sana Stojanovic Djurdjevic

Student: Strahinja Trninic
Indeks: mr17283
Grupa: 4R

Zadatak: 
        51. Internacionalna Matematicka Olimpijada
                    Astana, Kazahstan, 2010.

            Lista problema sa resenjima
            -Kombinatorni zadatak: C3-

(https://www.imo-official.org/problems/IMO2010SL.pdf)
\<close>


text \<open>
Kratak opisa zadatka:

Data je sahovska tabla dimenzije 100\<times>100. Potrebno je pronaci broj razlicitih nacina
na koje mogu da se poredjaju 2500 kraljeva, pazeci na uslove:
pazeci na sledece uslove:
- Kraljevi ne semju da napadaju jedni druge
- Svaki red i svaka kolona mora da sadrzi tacno 25 kraljeva
- Cak iako se jedna konfiguracija moze dobiti od druge rotacijama ili simetrijama,
  one se idalje tretiraju kao dve razlicite konfiguracije.
\<close>


section \<open>Tabla\<close>

text \<open>Definisemo tablu za igranje.\<close>


text \<open>Prvo polje je gore-levo i ima koordinate (0, 0) a poslednje je dole-desno i ima koordinate (11, 11).\<close>

datatype broj = nula ("\<zero>") | jedan ("\<one>") | dva ("\<two>") | tri ("\<three>") | cetiri ("\<four>") | pet ("\<five>") | sest ("\<six>") | sedam ("\<seven>") | osam ("\<eight>") | devet ("\<nine>") | 
                deset ("\<one>\<zero>") | jedanaest ("\<one>\<one>") (*| dvanaest ("\<one>\<two>") | trinaest ("\<one>\<three>") | cetrnaest ("\<one>\<four>") | petnaest ("\<one>\<five>") | sesnaest ("\<one>\<six>") | sedamnaest ("\<one>\<seven>") | osamnaest ("\<one>\<eight>") | deventaest ("\<one>\<nine>") |
                ddeset ("\<two>\<zero>") | djedan ("\<two>\<one>") | ddva ("\<two>\<two>") | dtri ("\<two>\<three>") | dcetiri ("\<two>\<four>") | dpet ("\<two>\<five>") | dsest ("\<two>\<six>") | dsedam ("\<two>\<seven>") | dosam ("\<two>\<eight>") | ddevet ("\<two>\<nine>") |
                tdeset ("\<three>\<zero>") | tjedan ("\<three>\<one>") | tdva ("\<three>\<two>") | ttri ("\<three>\<three>") | tcetiri ("\<three>\<four>") | tpet ("\<three>\<five>") | tsest ("\<three>\<six>") | tsedam ("\<three>\<seven>") | tosam ("\<three>\<eight>") | tdevet ("\<three>\<nine>") |
                cdeset ("\<four>\<zero>") | cjedan ("\<four>\<one>") | cdva ("\<four>\<two>") | ctri ("\<four>\<three>") | ccetiri ("\<four>\<four>") | cpet ("\<four>\<five>") | csest ("\<four>\<six>") | csedam ("\<four>\<seven>") | cosam ("\<four>\<eight>") | cdevet ("\<four>\<nine>") |
                pdeset ("\<five>\<zero>") | pjedan ("\<five>\<one>") | pdva ("\<five>\<two>") | ptri ("\<five>\<three>") | pcetiri ("\<five>\<four>") | ppet ("\<five>\<five>") | psest ("\<five>\<six>") | psedam ("\<five>\<seven>") | posam ("\<five>\<eight>") | pdevet ("\<five>\<nine>") |
                sdeset ("\<six>\<zero>") | sjedan ("\<six>\<one>") | sdva ("\<six>\<two>") | stri ("\<six>\<three>") | scetiri ("\<six>\<four>") | spet ("\<six>\<five>") | ssest ("\<six>\<six>") | ssedam ("\<six>\<seven>") | sosam ("\<six>\<eight>") | sdevet ("\<six>\<nine>") |
                sedeset ("\<seven>\<zero>") | sejedan ("\<seven>\<one>") | sedva ("\<seven>\<two>") | setri ("\<seven>\<three>") | secetiri ("\<seven>\<four>") | sepet ("\<seven>\<five>") | sesest ("7\<six>") | sesedam ("\<seven>\<seven>") | seosam ("\<seven>\<eight>") | sedevet ("\<seven>\<nine>") |
                odeset ("\<eight>\<zero>") | ojedan ("\<eight>\<one>") | odva ("\<eight>\<two>") | otri ("\<eight>\<three>") | ocetiri ("\<eight>\<four>") | opet ("\<eight>\<five>") | osest ("\<eight>\<six>") | osedam ("\<eight>\<seven>") | oosam ("\<eight>\<eight>") | odevet ("\<eight>\<nine>") |
                dedeset ("\<nine>\<zero>") | dejedan ("\<nine>\<one>") | dedva ("\<nine>\<two>") | detri ("\<nine>\<three>") | decetiri ("\<nine>\<four>") | depet ("\<nine>\<five>") | desest ("\<nine>\<six>") | desedam ("\<nine>\<seven>") | deosam ("\<nine>\<eight>") | dedevet ("\<nine>\<nine>")*)

type_synonym polje = "broj \<times> broj"


section \<open>Igra\<close>

text \<open>Definisemo locale u kome cemo definisati sve uslove. Nitpick bi onda trebalo da pronadje barem jednu
      trazenu konfiguraciju.\<close>

locale Igra = 
  (*Posto koristimo diskretan podskup prirodnih brojeva, moramo izpocetka da definisemo funkcije poput sledbenika, razlike brojeva, ...
    koje ce nam kasnije trebati za odredjivanje susednih polja zadatog polja.*)
(*  fixes sledbenik :: "broj \<Rightarrow> broj"
  assumes sledbenik_Eksplicitno: "sledbenik x = (if x = \<zero> then \<one> else if x = \<one> then \<two> else if x = \<two> then \<three> else if x = \<three> then \<four> else if x = \<four> then \<five> else if x = \<five> then \<six> else if x = \<six> then \<seven> else if x = \<seven> then \<eight> else if x = \<nine> then \<one>\<zero> else \<one>\<one>)"
  (*...*)

  fixes m0nus1 :: "broj \<Rightarrow> broj"
  assumes m0nus1_Eksplicitno: "m0nus1 x = (if x = \<one>\<one> then \<one>\<zero> else if x = \<one>\<zero> then \<nine> else if x = \<nine> then \<eight> else if x = \<eight> then \<seven> else if x = \<seven> then \<six> else if x = \<six> then \<five> else if x = \<five> then \<four> else if x = \<four> then \<three> else if x = \<three> then \<two> else if x = \<two> then \<one> else \<zero>)"
  (*...*)

  (*Definisemo poredak brojeva:*)
  fixes manje :: "broj \<Rightarrow> broj \<Rightarrow> bool" (infixl "\<prec>" 100)
  assumes manje_IRefl: "\<And>x.(\<not>(x \<prec> x))"
  assumes manje_Trans: "\<And>x y z.(x \<prec> y \<and> y \<prec> z \<longrightarrow> x \<prec> z)"
  assumes manje_Sledbenik: "\<And>x.((x \<noteq> \<one>\<one>)\<longrightarrow> x \<prec> (sledbenik x))"
  assumes manje_Najmanje: "\<And>x.((x \<noteq> \<zero>) \<longrightarrow> \<zero> \<prec> x)" (*Nepotrebno, ali pomaze!*)
  assumes manje_Najvece: "\<And>x.((x \<noteq> \<one>\<one>) \<longrightarrow> x \<prec> \<one>\<one>)" (*Nepotrebno, ali pomaze!*)

*)

  (*Definisemo unarnu relaciju "Kralj je na polju (x, y)"*)
  fixes kralj :: "broj \<Rightarrow> broj \<Rightarrow> bool"

  (*assumes vrsta_Tacno25: "\<And>x.\<exists>y1 y2 y3 y4 y5 y6 y7 y8 y9 y10 y11 y12 y13 y14 y15 y16 y17 y18 y19 y20 y21 y22 y23 y24 y25.
                  (kralj x y1 \<and> kralj x y2 \<and> kralj x y3 \<and> kralj x y4 \<and> kralj x y5 \<and> kralj x y6 \<and> kralj x y7 \<and> kralj x y8 \<and> kralj x y8 \<and> kralj x y9 \<and> kralj x y10 \<and> kralj x y11 \<and> kralj x y12 \<and> kralj x y13 \<and> kralj x y14 \<and> kralj x y15 \<and> kralj x y16 \<and> kralj x y17 \<and> kralj x y18 \<and> kralj x y19 \<and> kralj x y20 \<and> kralj x y21 \<and> kralj x y22 \<and> kralj x y23 \<and> kralj x y24 \<and> kralj x y25
                   \<and> (\<And>t.(t \<notin> {y1, y2, y3, y4, y5, y6, y7, y8, y9, y10, y11, y12, y13, y14, y15, y16, y17, y18, y19, y20, y21, y22, y23, y24, y25} \<longrightarrow> \<not>kralj x t)))"

  assumes kolona_Tacno25: "\<And>y.\<exists>x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 x15 x16 x17 x18 x19 x20 x21 x22 x23 x24 x25.
                  (kralj x1 y \<and> kralj x2 y \<and> kralj x3 y \<and> kralj x4 y \<and> kralj x5 y \<and> kralj x6 y \<and> kralj x7 y \<and> kralj x8 y \<and> kralj x8 y \<and> kralj x9 y \<and> kralj x10 y \<and> kralj x11 y \<and> kralj x12 y \<and> kralj x13 y \<and> kralj x14 y \<and> kralj x15 y \<and> kralj x16 y \<and> kralj x17 y \<and> kralj x18 y \<and> kralj x19 y \<and> kralj x20 y \<and> kralj x21 y \<and> kralj x22 y \<and> kralj x23 y \<and> kralj x24 y \<and> kralj x25 y
                   \<and> (\<And>t.(t \<notin> {x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25} \<longrightarrow> \<not>kralj t y)))" *)
  assumes vrsta_Tacno3: "\<forall>x.\<exists>y1 y2 y3.(kralj x y1 \<and> kralj x y2 \<and> kralj x y3 \<and>
                         (\<forall>t.(t \<notin> {y1, y2, y3} \<longrightarrow> \<not>kralj x t)))"
  assumes kolona_Tacno3: "\<forall>y.\<exists>x1 x2 x3.(kralj x1 y \<and> kralj x2 y \<and> kralj x3 y \<and>
                          (\<forall>t.(t \<notin> {x1, x2, x3} \<longrightarrow> \<not>kralj t y)))"
(*  assumes kralj_Tacno36: "\<exists>x1 y1 x2 y2 x3 y3 x4 y4 x5 y5 x6 y6 x7 y7 x8 y8 x9 y9 x10 y10 x11 y11 x12 y12 x13 y13 x14 y14 x15 y15 x16 y16 x17 y17 x18 y18 x19 y19 x20 y20 x21 y21 x22 y22 x23 y23 x24 y24 x25 y25 x26 y26 x27 y27 x28 y28 x29 y29 x30 y30 x31 y31 x32 y32 x33 y33 x34 y34 x35 y35 x36 y36.
                          (kralj x1 y1 \<and> kralj x2 y2 \<and> kralj x3 y3 \<and> kralj x4 y4 \<and> kralj x5 y5 \<and> kralj x6 y6 \<and> kralj x7 y7 \<and> kralj x8 y8 \<and> kralj x9 y9 \<and> kralj x10 y10 \<and> kralj x11 y11 \<and> kralj x12 y12 \<and> kralj x13 y13 \<and> kralj x14 y14 \<and> kralj x15 y15 \<and> kralj x16 y16 \<and> kralj x17 y17 \<and> kralj x18 y18 \<and> kralj x19 y19 \<and> kralj x20 y20 \<and> kralj x21 y21 \<and> kralj x22 y22 \<and> kralj x23 y23 \<and> kralj x24 y24 \<and> kralj x25 y25 \<and> kralj x26 y26 \<and> kralj x27 y27 \<and> kralj x28 y28 \<and> kralj x29 y29 \<and> kralj x30 y30 \<and> kralj x31 y31 \<and> kralj x32 y32 \<and> kralj x33 y33 \<and> kralj x34 y34 \<and> kralj x35 y35 \<and> kralj x36 y36)"*)

assumes kralj_Const: "(kralj \<zero> \<zero> \<longrightarrow> (\<not>kralj \<zero> \<one> \<and> \<not>kralj \<one> \<zero> \<and> \<not>kralj \<one> \<one>)) \<and>
                      (kralj \<zero> \<one> \<longrightarrow> (\<not>kralj \<zero> \<zero> \<and> \<not>kralj \<zero> \<two> \<and> \<not>kralj \<one> \<zero> \<and> \<not>kralj \<one> \<one> \<and> \<not>kralj \<one> \<two>)) \<and>
                      (kralj \<zero> \<two> \<longrightarrow> (\<not>kralj \<zero> \<one> \<and> \<not>kralj \<zero> \<three> \<and> \<not>kralj \<one> \<one> \<and> \<not>kralj \<one> \<two> \<and> \<not>kralj \<one> \<three>)) \<and>
                      (kralj \<zero> \<three> \<longrightarrow> (\<not>kralj \<zero> \<two> \<and> \<not>kralj \<zero> \<four> \<and> \<not>kralj \<one> \<two> \<and> \<not>kralj \<one> \<three> \<and> \<not>kralj \<one> \<four>)) \<and>
                      (kralj \<zero> \<four> \<longrightarrow> (\<not>kralj \<zero> \<three> \<and> \<not>kralj \<zero> \<five> \<and> \<not>kralj \<one> \<three> \<and> \<not>kralj \<one> \<four> \<and> \<not>kralj \<one> \<five>)) \<and>
                      (kralj \<zero> \<five> \<longrightarrow> (\<not>kralj \<zero> \<four> \<and> \<not>kralj \<zero> \<six> \<and> \<not>kralj \<one> \<four> \<and> \<not>kralj \<one> \<five> \<and> \<not>kralj \<one> \<six>)) \<and>
                      (kralj \<zero> \<six> \<longrightarrow> (\<not>kralj \<zero> \<five> \<and> \<not>kralj \<zero> \<seven> \<and> \<not>kralj \<one> \<five> \<and> \<not>kralj \<one> \<six> \<and> \<not>kralj \<one> \<seven>)) \<and>
                      (kralj \<zero> \<seven> \<longrightarrow> (\<not>kralj \<zero> \<six> \<and> \<not>kralj \<zero> \<eight> \<and> \<not>kralj \<one> \<six> \<and> \<not>kralj \<one> \<seven> \<and> \<not>kralj \<one> \<eight>)) \<and>
                      (kralj \<zero> \<eight> \<longrightarrow> (\<not>kralj \<zero> \<seven> \<and> \<not>kralj \<zero> \<nine> \<and> \<not>kralj \<one> \<seven> \<and> \<not>kralj \<one> \<eight> \<and> \<not>kralj \<one> \<nine>)) \<and>
                      (kralj \<zero> \<nine> \<longrightarrow> (\<not>kralj \<zero> \<eight> \<and> \<not>kralj \<zero> \<one>\<zero> \<and> \<not>kralj \<one> \<eight> \<and> \<not>kralj \<one> \<nine> \<and> \<not>kralj \<one> \<one>\<zero>)) \<and>
                      (kralj \<zero> \<one>\<zero> \<longrightarrow> (\<not>kralj \<zero> \<nine> \<and> \<not>kralj \<zero> \<one>\<one> \<and> \<not>kralj \<one> \<nine> \<and> \<not>kralj \<one> \<one>\<zero> \<and> \<not>kralj \<one> \<one>\<one>)) \<and>
                      (kralj \<zero> \<one>\<one> \<longrightarrow> (\<not>kralj \<zero> \<one>\<zero> \<and> \<not>kralj \<one> \<one>\<zero> \<and> \<not>kralj \<one> \<one>\<one>)) \<and>

                      (kralj \<one> \<zero> \<longrightarrow> (\<not>kralj \<one> \<one> \<and> \<not>kralj \<zero> \<zero> \<and> \<not>kralj \<zero> \<one> \<and> \<not>kralj \<two> \<zero> \<and> \<not>kralj \<two> \<one>)) \<and>
                      (kralj \<one> \<one> \<longrightarrow> (\<not>kralj \<one> \<zero> \<and> \<not>kralj \<one> \<two> \<and> \<not>kralj \<zero> \<zero> \<and> \<not>kralj \<zero> \<one> \<and> \<not>kralj \<zero> \<two> \<and> \<not>kralj \<two> \<zero> \<and> \<not>kralj \<two> \<one> \<and> \<not>kralj \<two> \<two>)) \<and>
                      (kralj \<one> \<two> \<longrightarrow> (\<not>kralj \<one> \<one> \<and> \<not>kralj \<one> \<three> \<and> \<not>kralj \<zero> \<one> \<and> \<not>kralj \<zero> \<two> \<and> \<not>kralj \<zero> \<three> \<and> \<not>kralj \<two> \<one> \<and> \<not>kralj \<two> \<two> \<and> \<not>kralj \<two> \<three>)) \<and>
                      (kralj \<one> \<three> \<longrightarrow> (\<not>kralj \<one> \<two> \<and> \<not>kralj \<one> \<four> \<and> \<not>kralj \<zero> \<two> \<and> \<not>kralj \<zero> \<three> \<and> \<not>kralj \<zero> \<four> \<and> \<not>kralj \<two> \<two> \<and> \<not>kralj \<two> \<three> \<and> \<not>kralj \<two> \<four>)) \<and>
                      (kralj \<one> \<four> \<longrightarrow> (\<not>kralj \<one> \<three> \<and> \<not>kralj \<one> \<five> \<and> \<not>kralj \<zero> \<three> \<and> \<not>kralj \<zero> \<four> \<and> \<not>kralj \<zero> \<five> \<and> \<not>kralj \<two> \<three> \<and> \<not>kralj \<two> \<four> \<and> \<not>kralj \<two> \<five>)) \<and>
                      (kralj \<one> \<five> \<longrightarrow> (\<not>kralj \<one> \<four> \<and> \<not>kralj \<one> \<six> \<and> \<not>kralj \<zero> \<four> \<and> \<not>kralj \<zero> \<five> \<and> \<not>kralj \<zero> \<six> \<and> \<not>kralj \<two> \<four> \<and> \<not>kralj \<two> \<five> \<and> \<not>kralj \<two> \<six>)) \<and>
                      (kralj \<one> \<six> \<longrightarrow> (\<not>kralj \<one> \<five> \<and> \<not>kralj \<one> \<seven> \<and> \<not>kralj \<zero> \<five> \<and> \<not>kralj \<zero> \<six> \<and> \<not>kralj \<zero> \<seven> \<and> \<not>kralj \<two> \<five> \<and> \<not>kralj \<two> \<six> \<and> \<not>kralj \<two> \<seven>)) \<and>
                      (kralj \<one> \<seven> \<longrightarrow> (\<not>kralj \<one> \<six> \<and> \<not>kralj \<one> \<eight> \<and> \<not>kralj \<zero> \<six> \<and> \<not>kralj \<zero> \<seven> \<and> \<not>kralj \<zero> \<eight> \<and> \<not>kralj \<two> \<six> \<and> \<not>kralj \<two> \<seven> \<and> \<not>kralj \<two> \<eight>)) \<and>
                      (kralj \<one> \<eight> \<longrightarrow> (\<not>kralj \<one> \<seven> \<and> \<not>kralj \<one> \<nine> \<and> \<not>kralj \<zero> \<seven> \<and> \<not>kralj \<zero> \<eight> \<and> \<not>kralj \<zero> \<nine> \<and> \<not>kralj \<two> \<seven> \<and> \<not>kralj \<two> \<eight> \<and> \<not>kralj \<two> \<nine>)) \<and>
                      (kralj \<one> \<nine> \<longrightarrow> (\<not>kralj \<one> \<eight> \<and> \<not>kralj \<one> \<one>\<zero> \<and> \<not>kralj \<zero> \<eight> \<and> \<not>kralj \<zero> \<nine> \<and> \<not>kralj \<zero> \<one>\<zero> \<and> \<not>kralj \<two> \<eight> \<and> \<not>kralj \<two> \<nine> \<and> \<not>kralj \<two> \<one>\<zero>)) \<and>
                      (kralj \<one> \<one>\<zero> \<longrightarrow> (\<not>kralj \<one> \<nine> \<and> \<not>kralj \<one> \<one>\<one> \<and> \<not>kralj \<zero> \<nine> \<and> \<not>kralj \<zero> \<one>\<zero> \<and> \<not>kralj \<zero> \<one>\<one> \<and> \<not>kralj \<two> \<nine> \<and> \<not>kralj \<two> \<one>\<zero> \<and> \<not>kralj \<two> \<one>\<one>)) \<and>
                      (kralj \<one> \<one>\<one> \<longrightarrow> (\<not>kralj \<one> \<one>\<zero> \<and> \<not>kralj \<zero> \<one>\<zero> \<and> \<not>kralj \<zero> \<one>\<one> \<and> \<not>kralj \<two> \<one>\<zero> \<and> \<not>kralj \<two> \<one>\<one>)) \<and>

                      (kralj \<two> \<zero> \<longrightarrow> (\<not>kralj \<two> \<one> \<and> \<not>kralj \<one> \<zero> \<and> \<not>kralj \<one> \<one> \<and> \<not>kralj \<three> \<zero> \<and> \<not>kralj \<three> \<one>)) \<and>
                      (kralj \<two> \<one> \<longrightarrow> (\<not>kralj \<two> \<zero> \<and> \<not>kralj \<two> \<two> \<and> \<not>kralj \<one> \<zero> \<and> \<not>kralj \<one> \<one> \<and> \<not>kralj \<one> \<two> \<and> \<not>kralj \<three> \<zero> \<and> \<not>kralj \<three> \<one> \<and> \<not>kralj \<three> \<two>)) \<and>
                      (kralj \<two> \<two> \<longrightarrow> (\<not>kralj \<two> \<one> \<and> \<not>kralj \<two> \<three> \<and> \<not>kralj \<one> \<one> \<and> \<not>kralj \<one> \<two> \<and> \<not>kralj \<one> \<three> \<and> \<not>kralj \<three> \<one> \<and> \<not>kralj \<three> \<two> \<and> \<not>kralj \<three> \<three>)) \<and>
                      (kralj \<two> \<three> \<longrightarrow> (\<not>kralj \<two> \<two> \<and> \<not>kralj \<two> \<four> \<and> \<not>kralj \<one> \<two> \<and> \<not>kralj \<one> \<three> \<and> \<not>kralj \<one> \<four> \<and> \<not>kralj \<three> \<two> \<and> \<not>kralj \<three> \<three> \<and> \<not>kralj \<three> \<four>)) \<and>
                      (kralj \<two> \<four> \<longrightarrow> (\<not>kralj \<two> \<three> \<and> \<not>kralj \<two> \<five> \<and> \<not>kralj \<one> \<three> \<and> \<not>kralj \<one> \<four> \<and> \<not>kralj \<one> \<five> \<and> \<not>kralj \<three> \<three> \<and> \<not>kralj \<three> \<four> \<and> \<not>kralj \<three> \<five>)) \<and>
                      (kralj \<two> \<five> \<longrightarrow> (\<not>kralj \<two> \<four> \<and> \<not>kralj \<two> \<six> \<and> \<not>kralj \<one> \<four> \<and> \<not>kralj \<one> \<five> \<and> \<not>kralj \<one> \<six> \<and> \<not>kralj \<three> \<four> \<and> \<not>kralj \<three> \<five> \<and> \<not>kralj \<three> \<six>)) \<and>
                      (kralj \<two> \<six> \<longrightarrow> (\<not>kralj \<two> \<five> \<and> \<not>kralj \<two> \<seven> \<and> \<not>kralj \<one> \<five> \<and> \<not>kralj \<one> \<six> \<and> \<not>kralj \<one> \<seven> \<and> \<not>kralj \<three> \<five> \<and> \<not>kralj \<three> \<six> \<and> \<not>kralj \<three> \<seven>)) \<and>
                      (kralj \<two> \<seven> \<longrightarrow> (\<not>kralj \<two> \<six> \<and> \<not>kralj \<two> \<eight> \<and> \<not>kralj \<one> \<six> \<and> \<not>kralj \<one> \<seven> \<and> \<not>kralj \<one> \<eight> \<and> \<not>kralj \<three> \<six> \<and> \<not>kralj \<three> \<seven> \<and> \<not>kralj \<three> \<eight>)) \<and>
                      (kralj \<two> \<eight> \<longrightarrow> (\<not>kralj \<two> \<seven> \<and> \<not>kralj \<two> \<nine> \<and> \<not>kralj \<one> \<seven> \<and> \<not>kralj \<one> \<eight> \<and> \<not>kralj \<one> \<nine> \<and> \<not>kralj \<three> \<seven> \<and> \<not>kralj \<three> \<eight> \<and> \<not>kralj \<three> \<nine>)) \<and>
                      (kralj \<two> \<nine> \<longrightarrow> (\<not>kralj \<two> \<eight> \<and> \<not>kralj \<two> \<one>\<zero> \<and> \<not>kralj \<one> \<eight> \<and> \<not>kralj \<one> \<nine> \<and> \<not>kralj \<one> \<one>\<zero> \<and> \<not>kralj \<three> \<eight> \<and> \<not>kralj \<three> \<nine> \<and> \<not>kralj \<three> \<one>\<zero>)) \<and>
                      (kralj \<two> \<one>\<zero> \<longrightarrow> (\<not>kralj \<two> \<nine> \<and> \<not>kralj \<two> \<one>\<one> \<and> \<not>kralj \<one> \<nine> \<and> \<not>kralj \<one> \<one>\<zero> \<and> \<not>kralj \<one> \<one>\<one> \<and> \<not>kralj \<three> \<nine> \<and> \<not>kralj \<three> \<one>\<zero> \<and> \<not>kralj \<three> \<one>\<one>)) \<and>
                      (kralj \<two> \<one>\<one> \<longrightarrow> (\<not>kralj \<two> \<one>\<zero> \<and> \<not>kralj \<one> \<one>\<zero> \<and> \<not>kralj \<one> \<one>\<one> \<and> \<not>kralj \<three> \<one>\<zero> \<and> \<not>kralj \<three> \<one>\<one>)) \<and>

                      (kralj \<three> \<zero> \<longrightarrow> (\<not>kralj \<three> \<one> \<and> \<not>kralj \<two> \<zero> \<and> \<not>kralj \<two> \<one> \<and> \<not>kralj \<four> \<zero> \<and> \<not>kralj \<four> \<one>)) \<and>
                      (kralj \<three> \<one> \<longrightarrow> (\<not>kralj \<three> \<zero> \<and> \<not>kralj \<three> \<two> \<and> \<not>kralj \<two> \<zero> \<and> \<not>kralj \<two> \<one> \<and> \<not>kralj \<two> \<two> \<and> \<not>kralj \<four> \<zero> \<and> \<not>kralj \<four> \<one> \<and> \<not>kralj \<four> \<two>)) \<and>
                      (kralj \<three> \<two> \<longrightarrow> (\<not>kralj \<three> \<one> \<and> \<not>kralj \<three> \<three> \<and> \<not>kralj \<two> \<one> \<and> \<not>kralj \<two> \<two> \<and> \<not>kralj \<two> \<three> \<and> \<not>kralj \<four> \<one> \<and> \<not>kralj \<four> \<two> \<and> \<not>kralj \<four> \<three>)) \<and>
                      (kralj \<three> \<three> \<longrightarrow> (\<not>kralj \<three> \<two> \<and> \<not>kralj \<three> \<four> \<and> \<not>kralj \<two> \<two> \<and> \<not>kralj \<two> \<three> \<and> \<not>kralj \<two> \<four> \<and> \<not>kralj \<four> \<two> \<and> \<not>kralj \<four> \<three> \<and> \<not>kralj \<four> \<four>)) \<and>
                      (kralj \<three> \<four> \<longrightarrow> (\<not>kralj \<three> \<three> \<and> \<not>kralj \<three> \<five> \<and> \<not>kralj \<two> \<three> \<and> \<not>kralj \<two> \<four> \<and> \<not>kralj \<two> \<five> \<and> \<not>kralj \<four> \<three> \<and> \<not>kralj \<four> \<four> \<and> \<not>kralj \<four> \<five>)) \<and>
                      (kralj \<three> \<five> \<longrightarrow> (\<not>kralj \<three> \<four> \<and> \<not>kralj \<three> \<six> \<and> \<not>kralj \<two> \<four> \<and> \<not>kralj \<two> \<five> \<and> \<not>kralj \<two> \<six> \<and> \<not>kralj \<four> \<four> \<and> \<not>kralj \<four> \<five> \<and> \<not>kralj \<four> \<six>)) \<and>
                      (kralj \<three> \<six> \<longrightarrow> (\<not>kralj \<three> \<five> \<and> \<not>kralj \<three> \<seven> \<and> \<not>kralj \<two> \<five> \<and> \<not>kralj \<two> \<six> \<and> \<not>kralj \<two> \<seven> \<and> \<not>kralj \<four> \<five> \<and> \<not>kralj \<four> \<six> \<and> \<not>kralj \<four> \<seven>)) \<and>
                      (kralj \<three> \<seven> \<longrightarrow> (\<not>kralj \<three> \<six> \<and> \<not>kralj \<three> \<eight> \<and> \<not>kralj \<two> \<six> \<and> \<not>kralj \<two> \<seven> \<and> \<not>kralj \<two> \<eight> \<and> \<not>kralj \<four> \<six> \<and> \<not>kralj \<four> \<seven> \<and> \<not>kralj \<four> \<eight>)) \<and>
                      (kralj \<three> \<eight> \<longrightarrow> (\<not>kralj \<three> \<seven> \<and> \<not>kralj \<three> \<nine> \<and> \<not>kralj \<two> \<seven> \<and> \<not>kralj \<two> \<eight> \<and> \<not>kralj \<two> \<nine> \<and> \<not>kralj \<four> \<seven> \<and> \<not>kralj \<four> \<eight> \<and> \<not>kralj \<four> \<nine>)) \<and>
                      (kralj \<three> \<nine> \<longrightarrow> (\<not>kralj \<three> \<eight> \<and> \<not>kralj \<three> \<one>\<zero> \<and> \<not>kralj \<two> \<eight> \<and> \<not>kralj \<two> \<nine> \<and> \<not>kralj \<two> \<one>\<zero> \<and> \<not>kralj \<four> \<eight> \<and> \<not>kralj \<four> \<nine> \<and> \<not>kralj \<four> \<one>\<zero>)) \<and>
                      (kralj \<three> \<one>\<zero> \<longrightarrow> (\<not>kralj \<three> \<nine> \<and> \<not>kralj \<three> \<one>\<one> \<and> \<not>kralj \<two> \<nine> \<and> \<not>kralj \<two> \<one>\<zero> \<and> \<not>kralj \<two> \<one>\<one> \<and> \<not>kralj \<four> \<nine> \<and> \<not>kralj \<four> \<one>\<zero> \<and> \<not>kralj \<four> \<one>\<one>)) \<and>
                      (kralj \<three> \<one>\<one> \<longrightarrow> (\<not>kralj \<three> \<one>\<zero> \<and> \<not>kralj \<two> \<one>\<zero> \<and> \<not>kralj \<two> \<one>\<one> \<and> \<not>kralj \<four> \<one>\<zero> \<and> \<not>kralj \<four> \<one>\<one>)) \<and>

                      (kralj \<four> \<zero> \<longrightarrow> (\<not>kralj \<four> \<one> \<and> \<not>kralj \<three> \<zero> \<and> \<not>kralj \<three> \<one> \<and> \<not>kralj \<five> \<zero> \<and> \<not>kralj \<five> \<one>)) \<and>
                      (kralj \<four> \<one> \<longrightarrow> (\<not>kralj \<four> \<zero> \<and> \<not>kralj \<four> \<two> \<and> \<not>kralj \<three> \<zero> \<and> \<not>kralj \<three> \<one> \<and> \<not>kralj \<three> \<two> \<and> \<not>kralj \<five> \<zero> \<and> \<not>kralj STRAX \<one> \<and> \<not>kralj \<five> \<two>)) \<and>
                      (kralj \<four> \<two> \<longrightarrow> (\<not>kralj \<four> \<one> \<and> \<not>kralj \<four> \<three> \<and> \<not>kralj \<three> \<one> \<and> \<not>kralj \<three> \<two> \<and> \<not>kralj \<three> \<three> \<and> \<not>kralj \<five> \<one> \<and> \<not>kralj \<five> \<two> \<and> \<not>kralj \<five> \<three>)) \<and>
                      (kralj \<four> \<three> \<longrightarrow> (\<not>kralj \<four> \<two> \<and> \<not>kralj \<four> \<four> \<and> \<not>kralj \<three> \<two> \<and> \<not>kralj \<three> \<three> \<and> \<not>kralj \<three> \<four> \<and> \<not>kralj \<five> \<two> \<and> \<not>kralj \<five> \<three> \<and> \<not>kralj \<five> \<four>)) \<and>
                      (kralj \<four> \<four> \<longrightarrow> (\<not>kralj \<four> \<three> \<and> \<not>kralj \<four> \<five> \<and> \<not>kralj \<three> \<three> \<and> \<not>kralj \<three> \<four> \<and> \<not>kralj \<three> \<five> \<and> \<not>kralj \<five> \<three> \<and> \<not>kralj \<five> \<four> \<and> \<not>kralj \<five> \<five>)) \<and>
                      (kralj \<four> \<five> \<longrightarrow> (\<not>kralj \<four> \<four> \<and> \<not>kralj \<four> \<six> \<and> \<not>kralj \<three> \<four> \<and> \<not>kralj \<three> \<five> \<and> \<not>kralj \<three> \<six> \<and> \<not>kralj \<five> \<four> \<and> \<not>kralj \<five> \<five> \<and> \<not>kralj \<five> \<six>)) \<and>
                      (kralj \<four> \<six> \<longrightarrow> (\<not>kralj \<four> \<five> \<and> \<not>kralj \<four> \<seven> \<and> \<not>kralj \<three> \<five> \<and> \<not>kralj \<three> \<six> \<and> \<not>kralj \<three> \<seven> \<and> \<not>kralj \<five> \<five> \<and> \<not>kralj \<five> \<six> \<and> \<not>kralj \<five> \<seven>)) \<and>
                      (kralj \<four> \<seven> \<longrightarrow> (\<not>kralj \<four> \<six> \<and> \<not>kralj \<four> \<eight> \<and> \<not>kralj \<three> \<six> \<and> \<not>kralj \<three> \<seven> \<and> \<not>kralj \<three> \<eight> \<and> \<not>kralj \<five> \<six> \<and> \<not>kralj \<five> \<seven> \<and> \<not>kralj \<five> \<eight>)) \<and>
                      (kralj \<four> \<eight> \<longrightarrow> (\<not>kralj \<four> \<seven> \<and> \<not>kralj \<four> \<nine> \<and> \<not>kralj \<three> \<seven> \<and> \<not>kralj \<three> \<eight> \<and> \<not>kralj \<three> \<nine> \<and> \<not>kralj \<five> \<seven> \<and> \<not>kralj \<five> \<eight> \<and> \<not>kralj \<five> \<nine>)) \<and>
                      (kralj \<four> \<nine> \<longrightarrow> (\<not>kralj \<four> \<eight> \<and> \<not>kralj \<four> \<one>\<zero> \<and> \<not>kralj \<three> \<eight> \<and> \<not>kralj \<three> \<nine> \<and> \<not>kralj \<three> \<one>\<zero> \<and> \<not>kralj \<five> \<eight> \<and> \<not>kralj \<five> \<nine> \<and> \<not>kralj \<five> \<one>\<zero>)) \<and>
                      (kralj \<four> \<one>\<zero> \<longrightarrow> (\<not>kralj \<four> \<nine> \<and> \<not>kralj \<four> \<one>\<one> \<and> \<not>kralj \<three> \<nine> \<and> \<not>kralj \<three> \<one>\<zero> \<and> \<not>kralj \<three> \<one>\<one> \<and> \<not>kralj \<five> \<nine> \<and> \<not>kralj \<five> \<one>\<zero> \<and> \<not>kralj \<five> \<one>\<one>)) \<and>
                      (kralj \<four> \<one>\<one> \<longrightarrow> (\<not>kralj \<four> \<one>\<zero> \<and> \<not>kralj \<three> \<one>\<zero> \<and> \<not>kralj \<three> \<one>\<one> \<and> \<not>kralj \<five> \<one>\<zero> \<and> \<not>kralj \<five> \<one>\<one>)) \<and>

                      (kralj \<five> \<zero> \<longrightarrow> (\<not>kralj \<five> \<one> \<and> \<not>kralj \<four> \<zero> \<and> \<not>kralj \<four> \<one> \<and> \<not>kralj \<six> \<zero> \<and> \<not>kralj \<six> \<one>)) \<and>
                      (kralj \<five> \<one> \<longrightarrow> (\<not>kralj \<five> \<zero> \<and> \<not>kralj \<five> \<two> \<and> \<not>kralj \<four> \<zero> \<and> \<not>kralj \<four> \<one> \<and> \<not>kralj \<four> \<two> \<and> \<not>kralj \<six> \<zero> \<and> \<not>kralj \<six> \<one> \<and> \<not>kralj \<six> \<two>)) \<and>
                      (kralj \<five> \<two> \<longrightarrow> (\<not>kralj \<five> \<one> \<and> \<not>kralj \<five> \<three> \<and> \<not>kralj \<four> \<one> \<and> \<not>kralj \<four> \<two> \<and> \<not>kralj \<four> \<three> \<and> \<not>kralj \<six> \<one> \<and> \<not>kralj \<six> \<two> \<and> \<not>kralj \<six> \<three>)) \<and>
                      (kralj \<five> \<three> \<longrightarrow> (\<not>kralj \<five> \<two> \<and> \<not>kralj \<five> \<four> \<and> \<not>kralj \<four> \<two> \<and> \<not>kralj \<four> \<three> \<and> \<not>kralj \<four> \<four> \<and> \<not>kralj \<six> \<two> \<and> \<not>kralj \<six> \<three> \<and> \<not>kralj \<six> \<four>)) \<and>
                      (kralj \<five> \<four> \<longrightarrow> (\<not>kralj \<five> \<three> \<and> \<not>kralj \<five> \<five> \<and> \<not>kralj \<four> \<three> \<and> \<not>kralj \<four> \<four> \<and> \<not>kralj \<four> \<five> \<and> \<not>kralj \<six> \<three> \<and> \<not>kralj \<six> \<four> \<and> \<not>kralj \<six> \<five>)) \<and>
                      (kralj \<five> \<five> \<longrightarrow> (\<not>kralj \<five> \<four> \<and> \<not>kralj \<five> \<six> \<and> \<not>kralj \<four> \<four> \<and> \<not>kralj \<four> \<five> \<and> \<not>kralj \<four> \<six> \<and> \<not>kralj \<six> \<four> \<and> \<not>kralj \<six> \<five> \<and> \<not>kralj \<six> \<six>)) \<and>
                      (kralj \<five> \<six> \<longrightarrow> (\<not>kralj \<five> \<five> \<and> \<not>kralj \<five> \<seven> \<and> \<not>kralj \<four> \<five> \<and> \<not>kralj \<four> \<six> \<and> \<not>kralj \<four> \<seven> \<and> \<not>kralj \<six> \<five> \<and> \<not>kralj \<six> \<six> \<and> \<not>kralj \<six> \<seven>)) \<and>
                      (kralj \<five> \<seven> \<longrightarrow> (\<not>kralj \<five> \<six> \<and> \<not>kralj \<five> \<eight> \<and> \<not>kralj \<four> \<six> \<and> \<not>kralj \<four> \<seven> \<and> \<not>kralj \<four> \<eight> \<and> \<not>kralj \<six> \<six> \<and> \<not>kralj \<six> \<seven> \<and> \<not>kralj \<six> \<eight>)) \<and>
                      (kralj \<five> \<eight> \<longrightarrow> (\<not>kralj \<five> \<seven> \<and> \<not>kralj \<five> \<nine> \<and> \<not>kralj \<four> \<seven> \<and> \<not>kralj \<four> \<eight> \<and> \<not>kralj \<four> \<nine> \<and> \<not>kralj \<six> \<seven> \<and> \<not>kralj \<six> \<eight> \<and> \<not>kralj \<six> \<nine>)) \<and>
                      (kralj \<five> \<nine> \<longrightarrow> (\<not>kralj \<five> \<eight> \<and> \<not>kralj \<five> \<one>\<zero> \<and> \<not>kralj \<four> \<eight> \<and> \<not>kralj \<four> \<nine> \<and> \<not>kralj \<four> \<one>\<zero> \<and> \<not>kralj \<six> \<eight> \<and> \<not>kralj \<six> \<nine> \<and> \<not>kralj \<six> \<one>\<zero>)) \<and>
                      (kralj \<five> \<one>\<zero> \<longrightarrow> (\<not>kralj \<five> \<nine> \<and> \<not>kralj \<five> \<one>\<one> \<and> \<not>kralj \<four> \<nine> \<and> \<not>kralj \<four> \<one>\<zero> \<and> \<not>kralj \<four> \<one>\<one> \<and> \<not>kralj \<six> \<nine> \<and> \<not>kralj \<six> \<one>\<zero> \<and> \<not>kralj \<six> \<one>\<one>)) \<and>
                      (kralj \<five> \<one>\<one> \<longrightarrow> (\<not>kralj \<five> \<one>\<zero> \<and> \<not>kralj \<four> \<one>\<zero> \<and> \<not>kralj \<four> \<one>\<one> \<and> \<not>kralj \<six> \<one>\<zero> \<and> \<not>kralj \<six> \<one>\<one>)) \<and>

                      (kralj \<six> \<zero> \<longrightarrow> (\<not>kralj \<six> \<one> \<and> \<not>kralj \<five> \<zero> \<and> \<not>kralj \<five> \<one> \<and> \<not>kralj \<seven> \<zero> \<and> \<not>kralj \<seven> \<one>)) \<and>
                      (kralj \<six> \<one> \<longrightarrow> (\<not>kralj \<six> \<zero> \<and> \<not>kralj \<six> \<two> \<and> \<not>kralj \<five> \<zero> \<and> \<not>kralj \<five> \<one> \<and> \<not>kralj \<five> \<two> \<and> \<not>kralj \<seven> \<zero> \<and> \<not>kralj \<seven> \<one> \<and> \<not>kralj \<seven> \<two>)) \<and>
                      (kralj \<six> \<two> \<longrightarrow> (\<not>kralj \<six> \<one> \<and> \<not>kralj \<six> \<three> \<and> \<not>kralj \<five> \<one> \<and> \<not>kralj \<five> \<two> \<and> \<not>kralj \<five> \<three> \<and> \<not>kralj \<seven> \<one> \<and> \<not>kralj \<seven> \<two> \<and> \<not>kralj \<seven> \<three>)) \<and>
                      (kralj \<six> \<three> \<longrightarrow> (\<not>kralj \<six> \<two> \<and> \<not>kralj \<six> \<four> \<and> \<not>kralj \<five> \<two> \<and> \<not>kralj \<five> \<three> \<and> \<not>kralj \<five> \<four> \<and> \<not>kralj \<seven> \<two> \<and> \<not>kralj \<seven> \<three> \<and> \<not>kralj \<seven> \<four>)) \<and>
                      (kralj \<six> \<four> \<longrightarrow> (\<not>kralj \<six> \<three> \<and> \<not>kralj \<six> \<five> \<and> \<not>kralj \<five> \<three> \<and> \<not>kralj \<five> \<four> \<and> \<not>kralj \<five> \<five> \<and> \<not>kralj \<seven> \<three> \<and> \<not>kralj \<seven> \<four> \<and> \<not>kralj \<seven> \<five>)) \<and>
                      (kralj \<six> \<five> \<longrightarrow> (\<not>kralj \<six> \<four> \<and> \<not>kralj \<six> \<six> \<and> \<not>kralj \<five> \<four> \<and> \<not>kralj \<five> \<five> \<and> \<not>kralj \<five> \<six> \<and> \<not>kralj \<seven> \<four> \<and> \<not>kralj \<seven> \<five> \<and> \<not>kralj \<seven> \<six>)) \<and>
                      (kralj \<six> \<six> \<longrightarrow> (\<not>kralj \<six> \<five> \<and> \<not>kralj \<six> \<seven> \<and> \<not>kralj \<five> \<five> \<and> \<not>kralj \<five> \<six> \<and> \<not>kralj \<five> \<seven> \<and> \<not>kralj \<seven> \<five> \<and> \<not>kralj \<seven> \<six> \<and> \<not>kralj \<seven> \<seven>)) \<and>
                      (kralj \<six> \<seven> \<longrightarrow> (\<not>kralj \<six> \<six> \<and> \<not>kralj \<six> \<eight> \<and> \<not>kralj \<five> \<six> \<and> \<not>kralj \<five> \<seven> \<and> \<not>kralj \<five> \<eight> \<and> \<not>kralj \<seven> \<six> \<and> \<not>kralj \<seven> \<seven> \<and> \<not>kralj \<seven> \<eight>)) \<and>
                      (kralj \<six> \<eight> \<longrightarrow> (\<not>kralj \<six> \<seven> \<and> \<not>kralj \<six> \<nine> \<and> \<not>kralj \<five> \<seven> \<and> \<not>kralj \<five> \<eight> \<and> \<not>kralj \<five> \<nine> \<and> \<not>kralj \<seven> \<seven> \<and> \<not>kralj \<seven> \<eight> \<and> \<not>kralj \<seven> \<nine>)) \<and>
                      (kralj \<six> \<nine> \<longrightarrow> (\<not>kralj \<six> \<eight> \<and> \<not>kralj \<six> \<one>\<zero> \<and> \<not>kralj \<five> \<eight> \<and> \<not>kralj \<five> \<nine> \<and> \<not>kralj \<five> \<one>\<zero> \<and> \<not>kralj \<seven> \<eight> \<and> \<not>kralj \<seven> \<nine> \<and> \<not>kralj \<seven> \<one>\<zero>)) \<and>
                      (kralj \<six> \<one>\<zero> \<longrightarrow> (\<not>kralj \<six> \<nine> \<and> \<not>kralj \<six> \<one>\<one> \<and> \<not>kralj \<five> \<nine> \<and> \<not>kralj \<five> \<one>\<zero> \<and> \<not>kralj \<five> \<one>\<one> \<and> \<not>kralj \<seven> \<nine> \<and> \<not>kralj \<seven> \<one>\<zero> \<and> \<not>kralj \<seven> \<one>\<one>)) \<and>
                      (kralj \<six> \<one>\<one> \<longrightarrow> (\<not>kralj \<six> \<one>\<zero> \<and> \<not>kralj \<five> \<one>\<zero> \<and> \<not>kralj \<five> \<one>\<one> \<and> \<not>kralj \<seven> \<one>\<zero> \<and> \<not>kralj \<seven> \<one>\<one>)) \<and>

                      (kralj \<seven> \<zero> \<longrightarrow> (\<not>kralj \<seven> \<one> \<and> \<not>kralj \<six> \<zero> \<and> \<not>kralj \<six> \<one> \<and> \<not>kralj \<eight> \<zero> \<and> \<not>kralj \<eight> \<one>)) \<and>
                      (kralj \<seven> \<one> \<longrightarrow> (\<not>kralj \<seven> \<zero> \<and> \<not>kralj \<seven> \<two> \<and> \<not>kralj \<six> \<zero> \<and> \<not>kralj \<six> \<one> \<and> \<not>kralj \<six> \<two> \<and> \<not>kralj \<eight> \<zero> \<and> \<not>kralj \<eight> \<one> \<and> \<not>kralj \<eight> \<two>)) \<and>
                      (kralj \<seven> \<two> \<longrightarrow> (\<not>kralj \<seven> \<one> \<and> \<not>kralj \<seven> \<three> \<and> \<not>kralj \<six> \<one> \<and> \<not>kralj \<six> \<two> \<and> \<not>kralj \<six> \<three> \<and> \<not>kralj \<eight> \<one> \<and> \<not>kralj \<eight> \<two> \<and> \<not>kralj \<eight> \<three>)) \<and>
                      (kralj \<seven> \<three> \<longrightarrow> (\<not>kralj \<seven> \<two> \<and> \<not>kralj \<seven> \<four> \<and> \<not>kralj \<six> \<two> \<and> \<not>kralj \<six> \<three> \<and> \<not>kralj \<six> \<four> \<and> \<not>kralj \<eight> \<two> \<and> \<not>kralj \<eight> \<three> \<and> \<not>kralj \<eight> \<four>)) \<and>
                      (kralj \<seven> \<four> \<longrightarrow> (\<not>kralj \<seven> \<three> \<and> \<not>kralj \<seven> \<five> \<and> \<not>kralj \<six> \<three> \<and> \<not>kralj \<six> \<four> \<and> \<not>kralj \<six> \<five> \<and> \<not>kralj \<eight> \<three> \<and> \<not>kralj \<eight> \<four> \<and> \<not>kralj \<eight> \<five>)) \<and>
                      (kralj \<seven> \<five> \<longrightarrow> (\<not>kralj \<seven> \<four> \<and> \<not>kralj \<seven> \<six> \<and> \<not>kralj \<six> \<four> \<and> \<not>kralj \<six> \<five> \<and> \<not>kralj \<six> \<six> \<and> \<not>kralj \<eight> \<four> \<and> \<not>kralj \<eight> \<five> \<and> \<not>kralj \<eight> \<six>)) \<and>
                      (kralj \<seven> \<six> \<longrightarrow> (\<not>kralj \<seven> \<five> \<and> \<not>kralj \<seven> \<seven> \<and> \<not>kralj \<six> \<five> \<and> \<not>kralj \<six> \<six> \<and> \<not>kralj \<six> \<seven> \<and> \<not>kralj \<eight> \<five> \<and> \<not>kralj \<eight> \<six> \<and> \<not>kralj \<eight> \<seven>)) \<and>
                      (kralj \<seven> \<seven> \<longrightarrow> (\<not>kralj \<seven> \<six> \<and> \<not>kralj \<seven> \<eight> \<and> \<not>kralj \<six> \<six> \<and> \<not>kralj \<six> \<seven> \<and> \<not>kralj \<six> \<eight> \<and> \<not>kralj \<eight> \<six> \<and> \<not>kralj \<eight> \<seven> \<and> \<not>kralj \<eight> \<eight>)) \<and>
                      (kralj \<seven> \<eight> \<longrightarrow> (\<not>kralj \<seven> \<seven> \<and> \<not>kralj \<seven> \<nine> \<and> \<not>kralj \<six> \<seven> \<and> \<not>kralj \<six> \<eight> \<and> \<not>kralj \<six> \<nine> \<and> \<not>kralj \<eight> \<seven> \<and> \<not>kralj \<eight> \<eight> \<and> \<not>kralj \<eight> \<nine>)) \<and>
                      (kralj \<seven> \<nine> \<longrightarrow> (\<not>kralj \<seven> \<eight> \<and> \<not>kralj \<seven> \<one>\<zero> \<and> \<not>kralj \<six> \<eight> \<and> \<not>kralj \<six> \<nine> \<and> \<not>kralj \<six> \<one>\<zero> \<and> \<not>kralj \<eight> \<eight> \<and> \<not>kralj \<eight> \<nine> \<and> \<not>kralj \<eight> \<one>\<zero>)) \<and>
                      (kralj \<seven> \<one>\<zero> \<longrightarrow> (\<not>kralj \<seven> \<nine> \<and> \<not>kralj \<seven> \<one>\<one> \<and> \<not>kralj \<six> \<nine> \<and> \<not>kralj \<six> \<one>\<zero> \<and> \<not>kralj \<six> \<one>\<one> \<and> \<not>kralj \<eight> \<nine> \<and> \<not>kralj \<eight> \<one>\<zero> \<and> \<not>kralj \<eight> \<one>\<one>)) \<and>
                      (kralj \<seven> \<one>\<one> \<longrightarrow> (\<not>kralj \<seven> \<one>\<zero> \<and> \<not>kralj \<six> \<one>\<zero> \<and> \<not>kralj \<six> \<one>\<one> \<and> \<not>kralj \<eight> \<one>\<zero> \<and> \<not>kralj \<eight> \<one>\<one>)) \<and>

                      (kralj \<eight> \<zero> \<longrightarrow> (\<not>kralj \<eight> \<one> \<and> \<not>kralj \<seven> \<zero> \<and> \<not>kralj \<seven> \<one> \<and> \<not>kralj \<nine> \<zero> \<and> \<not>kralj \<nine> \<one>)) \<and>
                      (kralj \<eight> \<one> \<longrightarrow> (\<not>kralj \<eight> \<zero> \<and> \<not>kralj \<eight> \<two> \<and> \<not>kralj \<seven> \<zero> \<and> \<not>kralj \<seven> \<one> \<and> \<not>kralj \<seven> \<two> \<and> \<not>kralj \<nine> \<zero> \<and> \<not>kralj \<nine> \<one> \<and> \<not>kralj \<nine> \<two>)) \<and>
                      (kralj \<eight> \<two> \<longrightarrow> (\<not>kralj \<eight> \<one> \<and> \<not>kralj \<eight> \<three> \<and> \<not>kralj \<seven> \<one> \<and> \<not>kralj \<seven> \<two> \<and> \<not>kralj \<seven> \<three> \<and> \<not>kralj \<nine> \<one> \<and> \<not>kralj \<nine> \<two> \<and> \<not>kralj \<nine> \<three>)) \<and>
                      (kralj \<eight> \<three> \<longrightarrow> (\<not>kralj \<eight> \<two> \<and> \<not>kralj \<eight> \<four> \<and> \<not>kralj \<seven> \<two> \<and> \<not>kralj \<seven> \<three> \<and> \<not>kralj \<seven> \<four> \<and> \<not>kralj \<nine> \<two> \<and> \<not>kralj \<nine> \<three> \<and> \<not>kralj \<nine> \<four>)) \<and>
                      (kralj \<eight> \<four> \<longrightarrow> (\<not>kralj \<eight> \<three> \<and> \<not>kralj \<eight> \<five> \<and> \<not>kralj \<seven> \<three> \<and> \<not>kralj \<seven> \<four> \<and> \<not>kralj \<seven> \<five> \<and> \<not>kralj \<nine> \<three> \<and> \<not>kralj \<nine> \<four> \<and> \<not>kralj \<nine> \<five>)) \<and>
                      (kralj \<eight> \<five> \<longrightarrow> (\<not>kralj \<eight> \<four> \<and> \<not>kralj \<eight> \<six> \<and> \<not>kralj \<seven> \<four> \<and> \<not>kralj \<seven> \<five> \<and> \<not>kralj \<seven> \<six> \<and> \<not>kralj \<nine> \<four> \<and> \<not>kralj \<nine> \<five> \<and> \<not>kralj \<nine> \<six>)) \<and>
                      (kralj \<eight> \<six> \<longrightarrow> (\<not>kralj \<eight> \<five> \<and> \<not>kralj \<eight> \<seven> \<and> \<not>kralj \<seven> \<five> \<and> \<not>kralj \<seven> \<six> \<and> \<not>kralj \<seven> \<seven> \<and> \<not>kralj \<nine> \<five> \<and> \<not>kralj \<nine> \<six> \<and> \<not>kralj \<nine> \<seven>)) \<and>
                      (kralj \<eight> \<seven> \<longrightarrow> (\<not>kralj \<eight> \<six> \<and> \<not>kralj \<eight> \<eight> \<and> \<not>kralj \<seven> \<six> \<and> \<not>kralj \<seven> \<seven> \<and> \<not>kralj \<seven> \<eight> \<and> \<not>kralj \<nine> \<six> \<and> \<not>kralj \<nine> \<seven> \<and> \<not>kralj \<nine> \<eight>)) \<and>
                      (kralj \<eight> \<eight> \<longrightarrow> (\<not>kralj \<eight> \<seven> \<and> \<not>kralj \<eight> \<nine> \<and> \<not>kralj \<seven> \<seven> \<and> \<not>kralj \<seven> \<eight> \<and> \<not>kralj \<seven> \<nine> \<and> \<not>kralj \<nine> \<seven> \<and> \<not>kralj \<nine> \<eight> \<and> \<not>kralj \<nine> \<nine>)) \<and>
                      (kralj \<eight> \<nine> \<longrightarrow> (\<not>kralj \<eight> \<eight> \<and> \<not>kralj \<eight> \<one>\<zero> \<and> \<not>kralj \<seven> \<eight> \<and> \<not>kralj \<seven> \<nine> \<and> \<not>kralj \<seven> \<one>\<zero> \<and> \<not>kralj \<nine> \<eight> \<and> \<not>kralj \<nine> \<nine> \<and> \<not>kralj \<nine> \<one>\<zero>)) \<and>
                      (kralj \<eight> \<one>\<zero> \<longrightarrow> (\<not>kralj \<eight> \<nine> \<and> \<not>kralj \<eight> \<one>\<one> \<and> \<not>kralj \<seven> \<nine> \<and> \<not>kralj \<seven> \<one>\<zero> \<and> \<not>kralj \<seven> \<one>\<one> \<and> \<not>kralj \<nine> \<nine> \<and> \<not>kralj \<nine> \<one>\<zero> \<and> \<not>kralj \<nine> \<one>\<one>)) \<and>
                      (kralj \<eight> \<one>\<one> \<longrightarrow> (\<not>kralj \<eight> \<one>\<zero> \<and> \<not>kralj \<seven> \<one>\<zero> \<and> \<not>kralj \<seven> \<one>\<one> \<and> \<not>kralj \<nine> \<one>\<zero> \<and> \<not>kralj \<nine> \<one>\<one>)) \<and>

                      (kralj \<nine> \<zero> \<longrightarrow> (\<not>kralj \<nine> \<one> \<and> \<not>kralj \<eight> \<zero> \<and> \<not>kralj \<eight> \<one> \<and> \<not>kralj \<one>\<zero> \<zero> \<and> \<not>kralj \<one>\<zero> \<one>)) \<and>
                      (kralj \<nine> \<one> \<longrightarrow> (\<not>kralj \<nine> \<zero> \<and> \<not>kralj \<nine> \<two> \<and> \<not>kralj \<eight> \<zero> \<and> \<not>kralj \<eight> \<one> \<and> \<not>kralj \<eight> \<two> \<and> \<not>kralj \<one>\<zero> \<zero> \<and> \<not>kralj \<one>\<zero> \<one> \<and> \<not>kralj \<one>\<zero> \<two>)) \<and>
                      (kralj \<nine> \<two> \<longrightarrow> (\<not>kralj \<nine> \<one> \<and> \<not>kralj \<nine> \<three> \<and> \<not>kralj \<eight> \<one> \<and> \<not>kralj \<eight> \<two> \<and> \<not>kralj \<eight> \<three> \<and> \<not>kralj \<one>\<zero> \<one> \<and> \<not>kralj \<one>\<zero> \<two> \<and> \<not>kralj \<one>\<zero> \<three>)) \<and>
                      (kralj \<nine> \<three> \<longrightarrow> (\<not>kralj \<nine> \<two> \<and> \<not>kralj \<nine> \<four> \<and> \<not>kralj \<eight> \<two> \<and> \<not>kralj \<eight> \<three> \<and> \<not>kralj \<eight> \<four> \<and> \<not>kralj \<one>\<zero> \<two> \<and> \<not>kralj \<one>\<zero> \<three> \<and> \<not>kralj \<one>\<zero> \<four>)) \<and>
                      (kralj \<nine> \<four> \<longrightarrow> (\<not>kralj \<nine> \<three> \<and> \<not>kralj \<nine> \<five> \<and> \<not>kralj \<eight> \<three> \<and> \<not>kralj \<eight> \<four> \<and> \<not>kralj \<eight> \<five> \<and> \<not>kralj \<one>\<zero> \<three> \<and> \<not>kralj \<one>\<zero> \<four> \<and> \<not>kralj \<one>\<zero> \<five>)) \<and>
                      (kralj \<nine> \<five> \<longrightarrow> (\<not>kralj \<nine> \<four> \<and> \<not>kralj \<nine> \<six> \<and> \<not>kralj \<eight> \<four> \<and> \<not>kralj \<eight> \<five> \<and> \<not>kralj \<eight> \<six> \<and> \<not>kralj \<one>\<zero> \<four> \<and> \<not>kralj \<one>\<zero> \<five> \<and> \<not>kralj \<one>\<zero> \<six>)) \<and>
                      (kralj \<nine> \<six> \<longrightarrow> (\<not>kralj \<nine> \<five> \<and> \<not>kralj \<nine> \<seven> \<and> \<not>kralj \<eight> \<five> \<and> \<not>kralj \<eight> \<six> \<and> \<not>kralj \<eight> \<seven> \<and> \<not>kralj \<one>\<zero> \<five> \<and> \<not>kralj \<one>\<zero> \<six> \<and> \<not>kralj \<one>\<zero> \<seven>)) \<and>
                      (kralj \<nine> \<seven> \<longrightarrow> (\<not>kralj \<nine> \<six> \<and> \<not>kralj \<nine> \<eight> \<and> \<not>kralj \<eight> \<six> \<and> \<not>kralj \<eight> \<seven> \<and> \<not>kralj \<eight> \<eight> \<and> \<not>kralj \<one>\<zero> \<six> \<and> \<not>kralj \<one>\<zero> \<seven> \<and> \<not>kralj \<one>\<zero> \<eight>)) \<and>
                      (kralj \<nine> \<eight> \<longrightarrow> (\<not>kralj \<nine> \<seven> \<and> \<not>kralj \<nine> \<nine> \<and> \<not>kralj \<eight> \<seven> \<and> \<not>kralj \<eight> \<eight> \<and> \<not>kralj \<eight> \<nine> \<and> \<not>kralj \<one>\<zero> \<seven> \<and> \<not>kralj \<one>\<zero> \<eight> \<and> \<not>kralj \<one>\<zero> \<nine>)) \<and>
                      (kralj \<nine> \<nine> \<longrightarrow> (\<not>kralj \<nine> \<eight> \<and> \<not>kralj \<nine> \<one>\<zero> \<and> \<not>kralj \<eight> \<eight> \<and> \<not>kralj \<eight> \<nine> \<and> \<not>kralj \<eight> \<one>\<zero> \<and> \<not>kralj \<one>\<zero> \<eight> \<and> \<not>kralj \<one>\<zero> \<nine> \<and> \<not>kralj \<one>\<zero> \<one>\<zero>)) \<and>
                      (kralj \<nine> \<one>\<zero> \<longrightarrow> (\<not>kralj \<nine> \<nine> \<and> \<not>kralj \<nine> \<one>\<one> \<and> \<not>kralj \<eight> \<nine> \<and> \<not>kralj \<eight> \<one>\<zero> \<and> \<not>kralj \<eight> \<one>\<one> \<and> \<not>kralj \<one>\<zero> \<nine> \<and> \<not>kralj \<one>\<zero> \<one>\<zero> \<and> \<not>kralj \<one>\<zero> \<one>\<one>)) \<and>
                      (kralj \<nine> \<one>\<one> \<longrightarrow> (\<not>kralj \<nine> \<one>\<zero> \<and> \<not>kralj \<eight> \<one>\<zero> \<and> \<not>kralj \<eight> \<one>\<one> \<and> \<not>kralj \<one>\<zero> \<one>\<zero> \<and> \<not>kralj \<one>\<zero> \<one>\<one>)) \<and>

                      (kralj \<one>\<zero> \<zero> \<longrightarrow> (\<not>kralj \<one>\<zero> \<one> \<and> \<not>kralj \<nine> \<zero> \<and> \<not>kralj \<nine> \<one> \<and> \<not>kralj \<one>\<one> \<zero> \<and> \<not>kralj \<one>\<one> \<one>)) \<and>
                      (kralj \<one>\<zero> \<one> \<longrightarrow> (\<not>kralj \<one>\<zero> \<zero> \<and> \<not>kralj \<one>\<zero> \<two> \<and> \<not>kralj STRAX \<zero> \<and> \<not>kralj \<nine> \<one> \<and> \<not>kralj \<nine> \<two> \<and> \<not>kralj \<one>\<one> \<zero> \<and> \<not>kralj \<one>\<one> \<one> \<and> \<not>kralj \<one>\<one> \<two>)) \<and>
                      (kralj \<one>\<zero> \<two> \<longrightarrow> (\<not>kralj \<one>\<zero> \<one> \<and> \<not>kralj \<one>\<zero> \<three> \<and> \<not>kralj \<nine> \<one> \<and> \<not>kralj \<nine> \<two> \<and> \<not>kralj \<nine> \<three> \<and> \<not>kralj \<one>\<one> \<one> \<and> \<not>kralj \<one>\<one> \<two> \<and> \<not>kralj \<one>\<one> \<three>)) \<and>
                      (kralj \<one>\<zero> \<three> \<longrightarrow> (\<not>kralj \<one>\<zero> \<two> \<and> \<not>kralj \<one>\<zero> \<four> \<and> \<not>kralj \<nine> \<two> \<and> \<not>kralj \<nine> \<three> \<and> \<not>kralj \<nine> \<four> \<and> \<not>kralj \<one>\<one> \<two> \<and> \<not>kralj \<one>\<one> \<three> \<and> \<not>kralj \<one>\<one> \<four>)) \<and>
                      (kralj \<one>\<zero> \<four> \<longrightarrow> (\<not>kralj \<one>\<zero> \<three> \<and> \<not>kralj \<one>\<zero> \<five> \<and> \<not>kralj \<nine> \<three> \<and> \<not>kralj \<nine> \<four> \<and> \<not>kralj \<nine> \<five> \<and> \<not>kralj \<one>\<one> \<three> \<and> \<not>kralj \<one>\<one> \<four> \<and> \<not>kralj \<one>\<one> \<five>)) \<and>
                      (kralj \<one>\<zero> \<five> \<longrightarrow> (\<not>kralj \<one>\<zero> \<four> \<and> \<not>kralj \<one>\<zero> \<six> \<and> \<not>kralj \<nine> \<four> \<and> \<not>kralj \<nine> \<five> \<and> \<not>kralj \<nine> \<six> \<and> \<not>kralj \<one>\<one> \<four> \<and> \<not>kralj \<one>\<one> \<five> \<and> \<not>kralj \<one>\<one> \<six>)) \<and>
                      (kralj \<one>\<zero> \<six> \<longrightarrow> (\<not>kralj \<one>\<zero> \<five> \<and> \<not>kralj \<one>\<zero> \<seven> \<and> \<not>kralj \<nine> \<five> \<and> \<not>kralj \<nine> \<six> \<and> \<not>kralj \<nine> \<seven> \<and> \<not>kralj \<one>\<one> \<five> \<and> \<not>kralj \<one>\<one> \<six> \<and> \<not>kralj \<one>\<one> \<seven>)) \<and>
                      (kralj \<one>\<zero> \<seven> \<longrightarrow> (\<not>kralj \<one>\<zero> \<six> \<and> \<not>kralj \<one>\<zero> \<eight> \<and> \<not>kralj \<nine> \<six> \<and> \<not>kralj \<nine> \<seven> \<and> \<not>kralj \<nine> \<eight> \<and> \<not>kralj \<one>\<one> \<six> \<and> \<not>kralj \<one>\<one> \<seven> \<and> \<not>kralj \<one>\<one> \<eight>)) \<and>
                      (kralj \<one>\<zero> \<eight> \<longrightarrow> (\<not>kralj \<one>\<zero> \<seven> \<and> \<not>kralj \<one>\<zero> \<nine> \<and> \<not>kralj \<nine> \<seven> \<and> \<not>kralj \<nine> \<eight> \<and> \<not>kralj \<nine> \<nine> \<and> \<not>kralj \<one>\<one> \<seven> \<and> \<not>kralj \<one>\<one> \<eight> \<and> \<not>kralj \<one>\<one> \<nine>)) \<and>
                      (kralj \<one>\<zero> \<nine> \<longrightarrow> (\<not>kralj \<one>\<zero> \<eight> \<and> \<not>kralj \<one>\<zero> \<one>\<zero> \<and> \<not>kralj \<nine> \<eight> \<and> \<not>kralj \<nine> \<nine> \<and> \<not>kralj \<nine> \<one>\<zero> \<and> \<not>kralj \<one>\<one> \<eight> \<and> \<not>kralj \<one>\<one> \<nine> \<and> \<not>kralj \<one>\<one> \<one>\<zero>)) \<and>
                      (kralj \<one>\<zero> \<one>\<zero> \<longrightarrow> (\<not>kralj \<one>\<zero> \<nine> \<and> \<not>kralj \<one>\<zero> \<one>\<one> \<and> \<not>kralj \<nine> \<nine> \<and> \<not>kralj \<nine> \<one>\<zero> \<and> \<not>kralj \<nine> \<one>\<one> \<and> \<not>kralj \<one>\<one> \<nine> \<and> \<not>kralj \<one>\<one> \<one>\<zero> \<and> \<not>kralj \<one>\<one> \<one>\<one>)) \<and>
                      (kralj \<one>\<zero> \<one>\<one> \<longrightarrow> (\<not>kralj \<one>\<zero> \<one>\<zero> \<and> \<not>kralj \<nine> \<one>\<zero> \<and> \<not>kralj \<nine> \<one>\<one> \<and> \<not>kralj \<one>\<one> \<one>\<zero> \<and> \<not>kralj \<one>\<one> \<one>\<one>)) \<and>

                      (kralj \<one>\<one> \<zero> \<longrightarrow> (\<not>kralj \<one>\<one> \<one> \<and> \<not>kralj \<one>\<zero> \<zero> \<and> \<not>kralj \<one>\<zero> \<one>)) \<and>
                      (kralj \<one>\<one> \<one> \<longrightarrow> (\<not>kralj \<one>\<one> \<zero> \<and> \<not>kralj \<one>\<one> \<two> \<and> \<not>kralj \<one>\<zero> \<zero> \<and> \<not>kralj \<one>\<zero> \<one> \<and> \<not>kralj \<one>\<zero> \<two>)) \<and>
                      (kralj \<one>\<one> \<two> \<longrightarrow> (\<not>kralj \<one>\<one> \<one> \<and> \<not>kralj \<one>\<one> \<three> \<and> \<not>kralj \<one>\<zero> \<one> \<and> \<not>kralj \<one>\<zero> \<two> \<and> \<not>kralj \<one>\<zero> \<three>)) \<and>
                      (kralj \<one>\<one> \<three> \<longrightarrow> (\<not>kralj \<one>\<one> \<two> \<and> \<not>kralj \<one>\<one> \<four> \<and> \<not>kralj \<one>\<zero> \<two> \<and> \<not>kralj \<one>\<zero> \<three> \<and> \<not>kralj \<one>\<zero> \<four>)) \<and>
                      (kralj \<one>\<one> \<four> \<longrightarrow> (\<not>kralj \<one>\<one> \<three> \<and> \<not>kralj \<one>\<one> \<five> \<and> \<not>kralj \<one>\<zero> \<three> \<and> \<not>kralj \<one>\<zero> \<four> \<and> \<not>kralj \<one>\<zero> \<five>)) \<and>
                      (kralj \<one>\<one> \<five> \<longrightarrow> (\<not>kralj \<one>\<one> \<four> \<and> \<not>kralj \<one>\<one> \<six> \<and> \<not>kralj \<one>\<zero> \<four> \<and> \<not>kralj \<one>\<zero> \<five> \<and> \<not>kralj \<one>\<zero> \<six>)) \<and>
                      (kralj \<one>\<one> \<six> \<longrightarrow> (\<not>kralj \<one>\<one> \<five> \<and> \<not>kralj \<one>\<one> \<seven> \<and> \<not>kralj \<one>\<zero> \<five> \<and> \<not>kralj \<one>\<zero> \<six> \<and> \<not>kralj \<one>\<zero> \<seven>)) \<and>
                      (kralj \<one>\<one> \<seven> \<longrightarrow> (\<not>kralj \<one>\<one> \<six> \<and> \<not>kralj \<one>\<one> \<eight> \<and> \<not>kralj \<one>\<zero> \<six> \<and> \<not>kralj \<one>\<zero> \<seven> \<and> \<not>kralj \<one>\<zero> \<eight>)) \<and>
                      (kralj \<one>\<one> \<eight> \<longrightarrow> (\<not>kralj \<one>\<one> \<seven> \<and> \<not>kralj \<one>\<one> \<nine> \<and> \<not>kralj \<one>\<zero> \<seven> \<and> \<not>kralj \<one>\<zero> \<eight> \<and> \<not>kralj \<one>\<zero> \<nine>)) \<and>
                      (kralj \<one>\<one> \<nine> \<longrightarrow> (\<not>kralj \<one>\<one> \<eight> \<and> \<not>kralj \<one>\<one> \<one>\<zero> \<and> \<not>kralj \<one>\<zero> \<eight> \<and> \<not>kralj \<one>\<zero> \<nine> \<and> \<not>kralj \<one>\<zero> \<one>\<zero>)) \<and>
                      (kralj \<one>\<one> \<one>\<zero> \<longrightarrow> (\<not>kralj \<one>\<one> \<nine> \<and> \<not>kralj \<one>\<one> \<one>\<one> \<and> \<not>kralj \<one>\<zero> \<nine> \<and> \<not>kralj \<one>\<zero> \<one>\<zero> \<and> \<not>kralj \<one>\<zero> \<one>\<one>)) \<and>
                      (kralj \<one>\<one> \<one>\<one> \<longrightarrow> (\<not>kralj \<one>\<one> \<one>\<zero> \<and> \<not>kralj \<one>\<zero> \<one>\<zero> \<and> \<not>kralj \<one>\<zero> \<one>\<one>))"

begin
text \<open>Neke provere\<close>

(*Pitamo se da li je nas model kontradiktoran.*)
lemma "False"
  oops (*Sledgehammer ne uspeva da pronadje kontradikciju!*)

(*lemma "\<two> \<prec> \<eight>"
  by (metis (full_types) broj.distinct(11) broj.distinct(13) broj.distinct(19) broj.distinct(21) broj.distinct(23) broj.distinct(25) broj.distinct(27) broj.distinct(29) broj.distinct(3) broj.distinct(35) broj.distinct(37) broj.distinct(39) broj.distinct(41) broj.distinct(43) broj.distinct(47) broj.distinct(49) broj.distinct(5) broj.distinct(51) broj.distinct(53) broj.distinct(55) broj.distinct(59) broj.distinct(61) broj.distinct(63) broj.distinct(65)  broj.distinct(69) broj.distinct(7) broj.distinct(71) broj.distinct(73) broj.distinct(77) broj.distinct(79) broj.distinct(83) broj.distinct(87) broj.distinct(9) manje_Sledbenik manje_Trans sledbenik_Eksplicitno)*)



section \<open>Nitpick\<close>

lemma Kombinacija1: "\<not>(
      kralj \<zero> \<zero> = x0_0 \<and> kralj \<zero> \<one> = x0_1 \<and> kralj \<zero> \<two> = x0_2 \<and> kralj \<zero> \<three> = x0_3 \<and> kralj \<zero> \<four> = x0_4 \<and> kralj \<zero> \<five> = x0_5 \<and> kralj \<zero> \<six> = x0_6 \<and> kralj \<zero> \<seven> = x0_7 \<and> kralj \<zero> \<eight> = x0_8 \<and> kralj \<zero> \<nine> = x0_9 \<and> kralj \<zero> \<one>\<zero> = x0_10 \<and> kralj \<zero> \<one>\<one> = x0_11 \<and>
      kralj \<one> \<zero> = x1_0 \<and> kralj \<one> \<one> = x1_1 \<and> kralj \<one> \<two> = x1_2 \<and> kralj \<one> \<three> = x1_3 \<and> kralj \<one> \<four> = x1_4 \<and> kralj \<one> \<five> = x1_5 \<and> kralj \<one> \<six> = x1_6 \<and> kralj \<one> \<seven> = x1_7 \<and> kralj \<one> \<eight> = x1_8 \<and> kralj \<one> \<nine> = x1_9 \<and> kralj \<one> \<one>\<zero> = x1_10 \<and> kralj \<one> \<one>\<one> = x1_11 \<and>
      kralj \<two> \<zero> = x2_0 \<and> kralj \<two> \<one> = x2_1 \<and> kralj \<two> \<two> = x2_2 \<and> kralj \<two> \<three> = x2_3 \<and> kralj \<two> \<four> = x2_4 \<and> kralj \<two> \<five> = x2_5 \<and> kralj \<two> \<six> = x2_6 \<and> kralj \<two> \<seven> = x2_7 \<and> kralj \<two> \<eight> = x2_8 \<and> kralj \<two> \<nine> = x2_9 \<and> kralj \<two> \<one>\<zero> = x2_10 \<and> kralj \<two> \<one>\<one> = x2_11 \<and>
      kralj \<three> \<zero> = x3_0 \<and> kralj \<three> \<one> = x3_1 \<and> kralj \<three> \<two> = x3_2 \<and> kralj \<three> \<three> = x3_3 \<and> kralj \<three> \<four> = x3_4 \<and> kralj \<three> \<five> = x3_5 \<and> kralj \<three> \<six> = x3_6 \<and> kralj \<three> \<seven> = x3_7 \<and> kralj \<three> \<eight> = x3_8 \<and> kralj \<three> \<nine> = x3_9 \<and> kralj \<three> \<one>\<zero> = x3_10 \<and> kralj \<three> \<one>\<one> = x3_11 \<and>
      kralj \<four> \<zero> = x4_0 \<and> kralj \<four> \<one> = x4_1 \<and> kralj \<four> \<two> = x4_2 \<and> kralj \<four> \<three> = x4_3 \<and> kralj \<four> \<four> = x4_4 \<and> kralj \<four> \<five> = x4_5 \<and> kralj \<four> \<six> = x4_6 \<and> kralj \<four> \<seven> = x4_7 \<and> kralj \<four> \<eight> = x4_8 \<and> kralj \<four> \<nine> = x4_9 \<and> kralj \<four> \<one>\<zero> = x4_10 \<and> kralj \<four> \<one>\<one> = x4_11 \<and>
      kralj \<five> \<zero> = x5_0 \<and> kralj \<five> \<one> = x5_1 \<and> kralj \<five> \<two> = x5_2 \<and> kralj \<five> \<three> = x5_3 \<and> kralj \<five> \<four> = x5_4 \<and> kralj \<five> \<five> = x5_5 \<and> kralj \<five> \<six> = x5_6 \<and> kralj \<five> \<seven> = x5_7 \<and> kralj \<five> \<eight> = x5_8 \<and> kralj \<five> \<nine> = x5_9 \<and> kralj \<five> \<one>\<zero> = x5_10 \<and> kralj \<five> \<one>\<one> = x5_11 \<and>
      kralj \<six> \<zero> = x6_0 \<and> kralj \<six> \<one> = x6_1 \<and> kralj \<six> \<two> = x6_2 \<and> kralj \<six> \<three> = x6_3 \<and> kralj \<six> \<four> = x6_4 \<and> kralj \<six> \<five> = x6_5 \<and> kralj \<six> \<six> = x6_6 \<and> kralj \<six> \<seven> = x6_7 \<and> kralj \<six> \<eight> = x6_8 \<and> kralj \<six> \<nine> = x6_9 \<and> kralj \<six> \<one>\<zero> = x6_10 \<and> kralj \<six> \<one>\<one> = x6_11 \<and>
      kralj \<seven> \<zero> = x7_0 \<and> kralj \<seven> \<one> = x7_1 \<and> kralj \<seven> \<two> = x7_2 \<and> kralj \<seven> \<three> = x7_3 \<and> kralj \<seven> \<four> = x7_4 \<and> kralj \<seven> \<five> = x7_5 \<and> kralj \<seven> \<six> = x7_6 \<and> kralj \<seven> \<seven> = x7_7 \<and> kralj \<seven> \<eight> = x7_8 \<and> kralj \<seven> \<nine> = x7_9 \<and> kralj \<seven> \<one>\<zero> = x7_10 \<and> kralj \<seven> \<one>\<one> = x7_11 \<and>
      kralj \<eight> \<zero> = x8_0 \<and> kralj \<eight> \<one> = x8_1 \<and> kralj \<eight> \<two> = x8_2 \<and> kralj \<eight> \<three> = x8_3 \<and> kralj \<eight> \<four> = x8_4 \<and> kralj \<eight> \<five> = x8_5 \<and> kralj \<eight> \<six> = x8_6 \<and> kralj \<eight> \<seven> = x8_7 \<and> kralj \<eight> \<eight> = x8_8 \<and> kralj \<eight> \<nine> = x8_9 \<and> kralj \<eight> \<one>\<zero> = x8_10 \<and> kralj \<eight> \<one>\<one> = x8_11 \<and>
      kralj \<nine> \<zero> = x9_0 \<and> kralj \<nine> \<one> = x9_1 \<and> kralj \<nine> \<two> = x9_2 \<and> kralj \<nine> \<three> = x9_3 \<and> kralj \<nine> \<four> = x9_4 \<and> kralj \<nine> \<five> = x9_5 \<and> kralj \<nine> \<six> = x9_6 \<and> kralj \<nine> \<seven> = x9_7 \<and> kralj \<nine> \<eight> = x9_8 \<and> kralj \<nine> \<nine> = x9_9 \<and> kralj \<nine> \<one>\<zero> = x9_10 \<and> kralj \<nine> \<one>\<one> = x9_11 \<and>
      kralj \<one>\<zero> \<zero> = x10_0 \<and> kralj \<one>\<zero> \<one> = x10_1 \<and> kralj \<one>\<zero> \<two> = x10_2 \<and> kralj \<one>\<zero> \<three> = x10_3 \<and> kralj \<one>\<zero> \<four> = x10_4 \<and> kralj \<one>\<zero> \<five> = x10_5 \<and> kralj \<one>\<zero> \<six> = x10_6 \<and> kralj \<one>\<zero> \<seven> = x10_7 \<and> kralj \<one>\<zero> \<eight> = x10_8 \<and> kralj \<one>\<zero> \<nine> = x10_9 \<and> kralj \<one>\<zero> \<one>\<zero> = x10_10 \<and> kralj \<one>\<zero> \<one>\<one> = x10_11 \<and>
      kralj \<one>\<one> \<zero> = x11_0 \<and> kralj \<one>\<one> \<one> = x11_1 \<and> kralj \<one>\<one> \<two> = x11_2 \<and> kralj \<one>\<one> \<three> = x11_3 \<and> kralj \<one>\<one> \<four> = x11_4 \<and> kralj \<one>\<one> \<five> = x11_5 \<and> kralj \<one>\<one> \<six> = x11_6 \<and> kralj \<one>\<one> \<seven> = x11_7 \<and> kralj \<one>\<one> \<eight> = x11_8 \<and> kralj \<one>\<one> \<nine> = x11_9 \<and> kralj \<one>\<one> \<one>\<zero> = x11_10 \<and> kralj \<one>\<one> \<one>\<one> = x11_11)"

  nitpick[expect=genuine]
  oops


end


end